$Import('pl.content.top');
//$Import('pl.profile.albumList');
$Import('pl.content.changeLanguage');
//左导开始
$Import('pl.leftNav.profilePersonal');
$Import('pl.leftNav.profileOpt');
//左导结束
$Import('pl.content.base');
STK.pageletM.start();