$Import('pl.content.base');
$Import('pl.content.changeLanguage');
$Import('pl.content.top');
$Import('pl.leftNav.common');
$Import('pl.leftNav.app');
$Import('pl.leftNav.game');
$Import('pl.content.myFavoritesListNarrow');
$Import('pl.content.favoritesTopNav');
STK.pageletM.start();
