$Import('pl.content.publisherTop');
$Import('pl.content.homeFeed');
$Import('pl.content.top');
$Import('pl.content.leftNav');
$Import('pl.content.personInfo');
//$Import('pl.content.liteFacePersonInfo');
//$Import('pl.content.myPersonalInfo');
$Import('pl.content.changeLanguage');
$Import('pl.content.homeInterest');
$Import('pl.content.customService');
$Import('pl.content.promotetopic');
$Import('pl.content.setSkin');
$Import('pl.content.versionTip');
$Import('pl.content.userGuider');
$Import('pl.content.base');
$Import('pl.content.topic');
$Import('pl.content.medal');
$Import('pl.guide.ucUser');
$Import('pl.guide.newUser');
$Import('pl.ad.backFill');
$Import('pl.content.pullylist');
$Import('pl.content.help');
$Import('pl.relation.recommendPopularUsers');
$Import('pl.content.interestgroup');
$Import('pl.content.allInOne');
//首页热门话题引导发微博弹层
$Import('pl.content.publishbubble');
$Import('pl.content.thirdModule');
$Import('pl.content.topTip');
//心情微博开始
$Import('pl.content.mood');
//心情微博结束
$Import('pl.content.tasks');
$Import('pl.content.bubBox');

//Feed筛选区引用
$Import('pl.apps.weiqun.groupsfeed');
$Import('pl.apps.chosen.groupsfeed');
STK.pageletM.start();
