$Import('pl.content.top');
$Import('pl.content.base');
$Import('pl.content.changeLanguage');
$Import('pl.leftNav.relation');
$Import('pl.leftNav.profileOpt');
$Import('pl.content.homeInterest');
$Import('pl.relation.recommendPopularUsers');
$Import('pl.relation.quietFollow');
STK.pageletM.start();