$Import('pl.content.top');
$Import('pl.content.personInfo');
$Import('pl.content.changeLanguage');
$Import('pl.leftNav.common');
$Import('pl.leftNav.app');
$Import('pl.leftNav.game');
$Import('pl.content.myAtCommentList');
$Import('pl.content.base');
STK.pageletM.start();
