$Import('pl.content.base');
$Import('pl.content.changeLanguage');
$Import('pl.content.personInfo');
$Import('pl.content.top');
$Import('pl.content.setSkin');
$Import('pl.content.favoritesTopNav');
$Import('pl.content.myFavoritesListNarrow');
$Import('pl.content.medal');
STK.pageletM.start();
